In [ ]:
import pandas

df = pandas.read_csv("/content/earthquake_1995-2023.csv")
df.head()

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 6.5 - 42 km W of Sola, Vanuatu",6.5,16-08-2023 12:47,7,4,green,0,657,us,114,7.177000,25.0,mww,192.955,-13.8814,167.1580,"Sola, Vanuatu",NaN,Vanuatu
1,"M 6.5 - 43 km S of Intipuc√°, El Salvador",6.5,19-07-2023 00:22,8,6,yellow,0,775,us,92,0.679000,40.0,mww,69.727,12.8140,-88.1265,"Intipuc√°, El Salvador",NaN,NaN
2,"M 6.6 - 25 km ESE of Loncopu√©, Argentina",6.6,17-07-2023 03:05,7,5,green,0,899,us,70,1.634000,28.0,mww,171.371,-38.1911,-70.3731,"Loncopu√©, Argentina",South America,Argentina
3,"M 7.2 - 98 km S of Sand Point, Alaska",7.2,16-07-2023 06:48,6,6,green,1,860,us,173,0.907000,36.0,mww,32.571,54.3844,-160.6990,"Sand Point, Alaska",NaN,NaN
4,M 7.3 - Alaska Peninsula,7.3,16-07-2023 06:48,0,5,NaN,1,820,at,79,0.879451,172.8,Mi,21.000,54.4900,-160.7960,Alaska Peninsula,NaN,NaN

In [ ]:
df.columns

Index(['title', 'magnitude', 'date_time', 'cdi', 'mmi', 'alert', 'tsunami',
       'sig', 'net', 'nst', 'dmin', 'gap', 'magType', 'depth', 'latitude',
       'longitude', 'location', 'continent', 'country'],
      dtype='object')

In [ ]:
final_df = df[['magnitude','cdi',"date_time","location"]]
final_df

     magnitude  cdi         date_time               location
0          6.5    7  16-08-2023 12:47          Sola, Vanuatu
1          6.5    8  19-07-2023 00:22  Intipuc√°, El Salvador
2          6.6    7  17-07-2023 03:05    Loncopu√©, Argentina
3          7.2    6  16-07-2023 06:48     Sand Point, Alaska
4          7.3    0  16-07-2023 06:48       Alaska Peninsula
..         ...  ...               ...                    ...
995        7.1    0  27-05-1995 13:03         Tungor, Russia
996        7.7    0  16-05-1995 20:12     Vao, New Caledonia
997        6.9    0  14-05-1995 11:33   Maubara, Timor Leste
998        6.6    0  13-05-1995 08:47          Aian√≠, Greece
999        7.1    0  05-05-1995 03:53  Cabatuan, Philippines

[1000 rows x 4 columns]

In [ ]:
final_df['location_prices'] = 1000

<ipython-input-15-1542cfdd6591>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['location_prices'] = 1000

In [ ]:
final_df

     magnitude  cdi         date_time               location  location_prices
0          6.5    7  16-08-2023 12:47          Sola, Vanuatu             1000
1          6.5    8  19-07-2023 00:22  Intipuc√°, El Salvador             1000
2          6.6    7  17-07-2023 03:05    Loncopu√©, Argentina             1000
3          7.2    6  16-07-2023 06:48     Sand Point, Alaska             1000
4          7.3    0  16-07-2023 06:48       Alaska Peninsula             1000
..         ...  ...               ...                    ...              ...
995        7.1    0  27-05-1995 13:03         Tungor, Russia             1000
996        7.7    0  16-05-1995 20:12     Vao, New Caledonia             1000
997        6.9    0  14-05-1995 11:33   Maubara, Timor Leste             1000
998        6.6    0  13-05-1995 08:47          Aian√≠, Greece             1000
999        7.1    0  05-05-1995 03:53  Cabatuan, Philippines             1000

[1000 rows x 5 columns]

In [ ]:
final_df['magnitude'].min()

6.5

In [ ]:
final_df['magnitude'].mean()

np.float64(6.940150000000001)

In [ ]:
final_df["testing"]  = final_df['magnitude'] + final_df['cdi']
final_df

<ipython-input-23-55b20bb825a2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["testing"]  = final_df['magnitude'] + final_df['cdi']

,magnitude,cdi,date_time,location,location_prices,testing
0,6.5,7,16-08-2023 12:47,"Sola, Vanuatu",1000,13.5
1,6.5,8,19-07-2023 00:22,"Intipuc√°, El Salvador",1000,14.5
2,6.6,7,17-07-2023 03:05,"Loncopu√©, Argentina",1000,13.6
3,7.2,6,16-07-2023 06:48,"Sand Point, Alaska",1000,13.2
4,7.3,0,16-07-2023 06:48,Alaska Peninsula,1000,7.3
...,...,...,...,...,...,...
995,7.1,0,27-05-1995 13:03,"Tungor, Russia",1000,7.1
996,7.7,0,16-05-1995 20:12,"Vao, New Caledonia",1000,7.7
997,6.9,0,14-05-1995 11:33,"Maubara, Timor Leste",1000,6.9
998,6.6,0,13-05-1995 08:47,"Aian√≠, Greece",1000,6.6
999,7.1,0,05-05-1995 03:53,"Cabatuan, Philippines",1000,7.1

In [ ]:
final_df["testing1"]  = final_df['magnitude'] / final_df['cdi']

<ipython-input-24-7718ad1eec2d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["testing1"]  = final_df['magnitude'] / final_df['cdi']

In [ ]:
final_df

,magnitude,cdi,date_time,location,location_prices,testing,testing1
0,6.5,7,16-08-2023 12:47,"Sola, Vanuatu",1000,13.5,0.928571
1,6.5,8,19-07-2023 00:22,"Intipuc√°, El Salvador",1000,14.5,0.812500
2,6.6,7,17-07-2023 03:05,"Loncopu√©, Argentina",1000,13.6,0.942857
3,7.2,6,16-07-2023 06:48,"Sand Point, Alaska",1000,13.2,1.200000
4,7.3,0,16-07-2023 06:48,Alaska Peninsula,1000,7.3,inf
...,...,...,...,...,...,...,...
995,7.1,0,27-05-1995 13:03,"Tungor, Russia",1000,7.1,inf
996,7.7,0,16-05-1995 20:12,"Vao, New Caledonia",1000,7.7,inf
997,6.9,0,14-05-1995 11:33,"Maubara, Timor Leste",1000,6.9,inf
998,6.6,0,13-05-1995 08:47,"Aian√≠, Greece",1000,6.6,inf
999,7.1,0,05-05-1995 03:53,"Cabatuan, Philippines",1000,7.1,inf

In [ ]:
final_df['location'].value_counts()

location
Kokopo, Papua New Guinea     29
Sola, Vanuatu                19
Kirakira, Solomon Islands    18
Panguna, Papua New Guinea    17
Kimbe, Papua New Guinea      15
                             ..
Thang, India                  1
Changuillo, Peru              1
Nishinoomote, Japan           1
Paphos, Cyprus                1
Palapag, Philippines          1
Name: count, Length: 502, dtype: int64

In [ ]:
final_df.sort_values('cdi')

,magnitude,cdi,date_time,location,location_prices,testing,testing1
752,6.8,0,20-06-2003 13:30,"Ovalle, Chile",1000,6.8,inf
708,7.1,0,26-11-2004 02:25,"Nabire, Indonesia",1000,7.1,inf
712,6.7,0,11-11-2004 17:34,"Kirakira, Solomon Islands",1000,6.7,inf
714,6.6,0,23-10-2004 08:56,"Ojiya, Japan",1000,6.6,inf
716,7.0,0,09-10-2004 21:26,"Masachapa, Nicaragua",1000,7.0,inf
...,...,...,...,...,...,...,...
28,6.7,9,06-02-2023 01:28,"Nurdaƒüƒ±, Turkey",1000,15.7,0.744444
488,7.1,9,23-10-2011 10:41,"Van, Turkey",1000,16.1,0.788889
61,6.7,9,13-03-2022 21:09,"Pariaman, Indonesia",1000,15.7,0.744444
407,7.1,9,15-10-2013 00:12,"Sagbayan, Philippines",1000,16.1,0.788889
27,7.5,9,06-02-2023 10:24,"Ekin√∂z√º, Turkey",1000,16.5,0.833333

In [ ]:
final_df.sort_values(['magnitude',"cdi"], ascending=True)

,magnitude,cdi,date_time,location,location_prices,testing,testing1
67,6.5,0,11-01-2022 12:39,"Nikolski, Alaska",1000,6.5,inf
68,6.5,0,11-01-2022 12:39,"Nikolski, Alaska",1000,6.5,inf
98,6.5,0,20-06-2021 17:05,"Kermadec Islands, New Zealand",1000,6.5,inf
108,6.5,0,04-03-2021 23:12,Kermadec Islands region,1000,6.5,inf
146,6.5,0,08-11-2019 10:44,"Ndoi Island, Fiji",1000,6.5,inf
...,...,...,...,...,...,...,...
692,8.6,0,28-03-2005 16:09,"Singkil, Indonesia",1000,8.6,inf
476,8.6,9,11-04-2012 08:38,off the west coast of northern Sumatra,1000,17.6,0.955556
552,8.8,8,27-02-2010 06:34,"Quirihue, Chile",1000,16.8,1.100000
703,9.1,0,26-12-2004 00:58,2004 Sumatra - Andaman Islands Earthquake,1000,9.1,inf
511,9.1,9,11-03-2011 05:46,"2011 Great Tohoku Earthquake, Japan",1000,18.1,1.011111

In [ ]:
final_df.sort_values(['location'], key= lambda text:text.str.lower())

,magnitude,cdi,date_time,location,location_prices,testing,testing1
703,9.1,0,26-12-2004 00:58,2004 Sumatra - Andaman Islands Earthquake,1000,9.1,inf
511,9.1,9,11-03-2011 05:46,"2011 Great Tohoku Earthquake, Japan",1000,18.1,1.011111
225,7.3,8,12-11-2017 18:18,"?alabja, Iraq",1000,15.3,0.912500
510,7.9,8,11-03-2011 06:15,"?arai, Japan",1000,15.9,0.987500
455,7.3,6,07-12-2012 08:18,"?funato, Japan",1000,13.3,1.216667
...,...,...,...,...,...,...,...
37,7.0,3,12-11-2022 07:09,NaN,1000,10.0,2.333333
39,6.6,0,09-11-2022 10:14,NaN,1000,6.6,inf
54,6.9,2,19-05-2022 10:13,NaN,1000,8.9,3.450000
103,6.9,7,01-05-2021 01:27,NaN,1000,13.9,0.985714
281,6.9,3,28-05-2016 05:38,NaN,1000,9.9,2.300000

In [ ]:
def summation(a , b):
  result = a + b
  print(result)

summation(1 , 3)

4

In [ ]:
1 + 3

4

In [ ]:
summation(39 , 29)

68

In [ ]:
summation(0 , 1)

1

In [1]:
import requests