### Creating dataframe from dictionary

In [1]:
import pandas as pd

# Create a dictionary with student data
student_data = {
    "Name": ["Alex", "Ben", "Clara", "Deric", "Eva", "Frank"],
    "Age": [20, 21, 19, 22, 23, 20],
    "Major": ["CS", "Math", "Physics", "Economics", "Biology", "Chemistry"],
    "Score": [85, 92, 78, 95, 88, 90],
    "Hometown": ["York", "Angeles", "Chicago", "Houston", "Boston", "Francisco"],
    "Graduation Year": [2022, 2023, 2022, 2023, 2024, 2023],
    "Scholarship": [False, True, False, True, False, False]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(student_data)

df

    Name  Age      Major  Score   Hometown  Graduation Year  Scholarship
0   Alex   20         CS     85       York             2022        False
1    Ben   21       Math     92    Angeles             2023         True
2  Clara   19    Physics     78    Chicago             2022        False
3  Deric   22  Economics     95    Houston             2023         True
4    Eva   23    Biology     88     Boston             2024        False
5  Frank   20  Chemistry     90  Francisco             2023        False

**describe()**: This function provides a statistical summary of the numerical columns in the DataFrame.

In [2]:
print(df.describe())

             Age      Score  Graduation Year
count   6.000000   6.000000         6.000000
mean   20.833333  88.000000      2022.833333
std     1.471960   5.966574         0.752773
min    19.000000  78.000000      2022.000000
25%    20.000000  85.750000      2022.250000
50%    20.500000  89.000000      2023.000000
75%    21.750000  91.500000      2023.000000
max    23.000000  95.000000      2024.000000

**info()**: This function displays a concise summary of a DataFrame, including data types, non-null values, and memory usage.

In [3]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             6 non-null      object
 1   Age              6 non-null      int64
 2   Major            6 non-null      object
 3   Score            6 non-null      int64
 4   Hometown         6 non-null      object
 5   Graduation Year  6 non-null      int64
 6   Scholarship      6 non-null      bool
dtypes: bool(1), int64(3), object(3)
memory usage: 426.0+ bytes
None

In [4]:
# Display DataFrame Dimensions
print(df.shape)

(6, 7)

In [5]:
# Select a single column
print(df['Major'])

0           CS
1         Math
2      Physics
3    Economics
4      Biology
5    Chemistry
Name: Major, dtype: object

In [6]:
# Check the column names
df.columns

Index(['Name', 'Age', 'Major', 'Score', 'Hometown', 'Graduation Year',
       'Scholarship'],
      dtype='object')

### Read the CSV file

In [8]:
df = pd.read_csv("earthquake_1995-2023.csv")
df

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 6.5 - 42 km W of Sola, Vanuatu",6.5,16-08-2023 12:47,7,4,green,0,657,us,114,7.177000,25.0,mww,192.955,-13.8814,167.1580,"Sola, Vanuatu",NaN,Vanuatu
1,"M 6.5 - 43 km S of Intipucá, El Salvador",6.5,19-07-2023 00:22,8,6,yellow,0,775,us,92,0.679000,40.0,mww,69.727,12.8140,-88.1265,"Intipucá, El Salvador",NaN,NaN
2,"M 6.6 - 25 km ESE of Loncopué, Argentina",6.6,17-07-2023 03:05,7,5,green,0,899,us,70,1.634000,28.0,mww,171.371,-38.1911,-70.3731,"Loncopué, Argentina",South America,Argentina
3,"M 7.2 - 98 km S of Sand Point, Alaska",7.2,16-07-2023 06:48,6,6,green,1,860,us,173,0.907000,36.0,mww,32.571,54.3844,-160.6990,"Sand Point, Alaska",NaN,NaN
4,M 7.3 - Alaska Peninsula,7.3,16-07-2023 06:48,0,5,NaN,1,820,at,79,0.879451,172.8,Mi,21.000,54.4900,-160.7960,Alaska Peninsula,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,"M 7.1 - 85 km S of Tungor, Russia",7.1,27-05-1995 13:03,0,9,NaN,0,776,us,0,0.000000,0.0,mwb,11.000,52.6290,142.8270,"Tungor, Russia",Asia,Russia
996,"M 7.7 - 249 km E of Vao, New Caledonia",7.7,16-05-1995 20:12,0,4,NaN,0,912,us,0,0.000000,0.0,mw,20.200,-23.0080,169.9000,"Vao, New Caledonia",NaN,NaN
997,"M 6.9 - 27 km NNW of Maubara, Timor Leste",6.9,14-05-1995 11:33,0,6,NaN,0,732,us,0,0.000000,0.0,mw,11.200,-8.3780,125.1270,"Maubara, Timor Leste",NaN,Indonesia
998,"M 6.6 - 10 km W of Aianí, Greece",6.6,13-05-1995 08:47,0,9,NaN,0,670,us,0,0.000000,0.0,mw,14.000,40.1490,21.6950,"Aianí, Greece",Europe,Greece
999,"M 7.1 - 14 km NE of Cabatuan, Philippines",7.1,05-05-1995 03:53,0,7,NaN,0,776,us,0,0.000000,0.0,mw,16.000,12.6260,125.2970,"Cabatuan, Philippines",NaN,Philippines

In [9]:
# Read the head
df.head()

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 6.5 - 42 km W of Sola, Vanuatu",6.5,16-08-2023 12:47,7,4,green,0,657,us,114,7.177000,25.0,mww,192.955,-13.8814,167.1580,"Sola, Vanuatu",NaN,Vanuatu
1,"M 6.5 - 43 km S of Intipucá, El Salvador",6.5,19-07-2023 00:22,8,6,yellow,0,775,us,92,0.679000,40.0,mww,69.727,12.8140,-88.1265,"Intipucá, El Salvador",NaN,NaN
2,"M 6.6 - 25 km ESE of Loncopué, Argentina",6.6,17-07-2023 03:05,7,5,green,0,899,us,70,1.634000,28.0,mww,171.371,-38.1911,-70.3731,"Loncopué, Argentina",South America,Argentina
3,"M 7.2 - 98 km S of Sand Point, Alaska",7.2,16-07-2023 06:48,6,6,green,1,860,us,173,0.907000,36.0,mww,32.571,54.3844,-160.6990,"Sand Point, Alaska",NaN,NaN
4,M 7.3 - Alaska Peninsula,7.3,16-07-2023 06:48,0,5,NaN,1,820,at,79,0.879451,172.8,Mi,21.000,54.4900,-160.7960,Alaska Peninsula,NaN,NaN

In [10]:
# Read the tail
df.tail()

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
995,"M 7.1 - 85 km S of Tungor, Russia",7.1,27-05-1995 13:03,0,9,NaN,0,776,us,0,0.0,0.0,mwb,11.0,52.629,142.827,"Tungor, Russia",Asia,Russia
996,"M 7.7 - 249 km E of Vao, New Caledonia",7.7,16-05-1995 20:12,0,4,NaN,0,912,us,0,0.0,0.0,mw,20.2,-23.008,169.900,"Vao, New Caledonia",NaN,NaN
997,"M 6.9 - 27 km NNW of Maubara, Timor Leste",6.9,14-05-1995 11:33,0,6,NaN,0,732,us,0,0.0,0.0,mw,11.2,-8.378,125.127,"Maubara, Timor Leste",NaN,Indonesia
998,"M 6.6 - 10 km W of Aianí, Greece",6.6,13-05-1995 08:47,0,9,NaN,0,670,us,0,0.0,0.0,mw,14.0,40.149,21.695,"Aianí, Greece",Europe,Greece
999,"M 7.1 - 14 km NE of Cabatuan, Philippines",7.1,05-05-1995 03:53,0,7,NaN,0,776,us,0,0.0,0.0,mw,16.0,12.626,125.297,"Cabatuan, Philippines",NaN,Philippines